### ISSUE TITLE
A wiki page on Domain knowledge will be helpful

### ISSUE THREAD

**Issue by Hasnayeen** [code-shoily/karma-werks-core#5]
A wiki page where all the domain related knowledge of this app is documented will be helpful to understand the features of the application for both contributor(new & old) and user, also a glossary page documenting terms related to the project will be helpful too.

**Comment by code-shoily** [comment]
Yes I know, but I intend to finish up a noticeable and workable portion of the GraphQL API first, so that we have a passable tool to work with before asking for contribution. And most of the code has tests, typespecs and docstrings so anyone with Elixir/Phoenix knowledge can pick it up fast (hopefully :pray: ).

**Comment by Hasnayeen** [comment]
sounds good
